name: Release for Windows and Android

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 Rust 环境
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        override: true

    # 安装 Dioxus CLI
    - name: Install Cargo Binstall
      uses: cargo-bins/cargo-binstall@main

    - name: Install Dioxus CLI
      run: cargo binstall dioxus-cli --force

    # 构建 Windows 目标
    - name: Build for Windows
      run: dx build --platform windows -r

    # 打包 Windows 构建产物
    - name: Create ZIP Archive
      run: |
        Compress-Archive -Path .\target\dx\smarter-buaa\release\windows\app -DestinationPath SmarterBuaa-x86_64-windows-msvc.zip

    # 上传 Windows 构建产物
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SmarterBuaa-x86_64-windows-msvc
        path: ./SmarterBuaa-x86_64-windows-msvc.zip

  build-android:
    runs-on: windows-latest

    env:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 Rust 环境
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        override: true

    # 安装 Android 目标
    - name: Install Android Target
      run: rustup target install aarch64-linux-android

    # 安装 Dioxus CLI
    - name: Install Cargo Binstall
      uses: cargo-bins/cargo-binstall@main

    - name: Install Dioxus CLI
      run: cargo binstall dioxus-cli --force

    # 设置 Java 环境
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # 设置 Android SDK 和 NDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Set up Android NDK
      run: |
        echo "y" | sdkmanager --install "ndk;28.0.12433566"
        echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/28.0.12433566" >> $GITHUB_ENV

    # 生成 Android 项目并修复图标文件和编译脚本
    - name: Gen Android and Fix Icons
      run: |
        dx bundle --platform android --arch arm64 -r
        Remove-Item -Recurse -Force .\target\dx\smarter-buaa\release\android\app\app\src\main\res\mipmap-hdpi
        Remove-Item -Recurse -Force .\target\dx\smarter-buaa\release\android\app\app\src\main\res\mipmap-mdpi
        Remove-Item -Recurse -Force .\target\dx\smarter-buaa\release\android\app\app\src\main\res\mipmap-xhdpi
        Remove-Item -Recurse -Force .\target\dx\smarter-buaa\release\android\app\app\src\main\res\mipmap-xxhdpi
        Remove-Item -Recurse -Force .\target\dx\smarter-buaa\release\android\app\app\src\main\res\mipmap-xxxhdpi
        Remove-Item -Force .\target\dx\smarter-buaa\release\android\app\app\src\main\res\mipmap-anydpi-v26\ic_launcher.xml
        Copy-Item -Recurse -Force .\assets\icons\android\* .\target\dx\smarter-buaa\release\android\app\app\src\main\res
        Copy-Item -Force .\assets\build.gradle.kts .\target\dx\smarter-buaa\release\android\app\app

    # 写入密钥文件并设置环境变量
    - name: Setup Keystore and Environment Variables
      run: |
        $KEYSTORE_FILE = [System.Convert]::FromBase64String($env:KEYSTORE_FILE)
        $KEYSTORE_PATH = ".\target\dx\smarter-buaa\release\android\app\app\fontlos.jks"
        [System.IO.File]::WriteAllBytes($KEYSTORE_PATH, $KEYSTORE_FILE)
        echo "KEYSTORE_PASSWORD=$env:KEYSTORE_PASSWORD" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "KEY_ALIAS=$env:KEY_ALIAS" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "KEY_PASSWORD=$env:KEY_PASSWORD" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    # 重新编译 APK 并签名
    - name: Rebuild APK with Signing
      run: |
        cd .\target\dx\smarter-buaa\release\android\app
        .\gradlew.bat clean
        .\gradlew.bat assembleRelease
        cd ..\..\..\..\..\..\
        Copy-Item -Force .\target\dx\smarter-buaa\release\android\app\app\build\outputs\apk\release\app-release.apk .\SmarterBuaa-aarch64-linux-android.apk

    # 上传 Android 构建产物
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SmarterBuaa-aarch64-linux-android
        path: ./SmarterBuaa-aarch64-linux-android.apk

  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-android]
    env:
      RELEASE_NAME: ""
      TAG_NAME: ""
      PRERELEASE: ""

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 下载构建产物
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    # 判断是否为预发布
    - name: Determine Release Type
      id: determine_release
      run: |
        if ${{ github.event_name == 'workflow_dispatch' }}; then
          echo "This is a pre-release"
          echo "RELEASE_NAME=SmarterBuaa Nightly Build.$(date -u +'%Y.%m.%d')" >> $GITHUB_ENV
          echo "TAG_NAME=nightly" >> $GITHUB_ENV
          echo "PRERELEASE=true" >> $GITHUB_ENV
        else
          echo "This is a formal release"
          echo "RELEASE_NAME=SmarterBuaa Release ${{ github.ref_name }}" >> $GITHUB_ENV
          echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "PRERELEASE=false" >> $GITHUB_ENV
        fi

    # 创建 Release 并上传构建产物
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.RELEASE_NAME }}
        tag_name: ${{ env.TAG_NAME }}
        draft: false
        prerelease: ${{ env.PRERELEASE == 'true' }}
        files: |
          ./artifacts/SmarterBuaa-x86_64-windows-msvc/SmarterBuaa-x86_64-windows-msvc.zip
          ./artifacts/SmarterBuaa-aarch64-linux-android/SmarterBuaa-aarch64-linux-android.apk
